# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"  # Specify your Python version

sphinx:
  configuration: docs/source/conf.py  # Path to your conf.py file

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt  # Path to your requirements file
